document.getElementById("b1").onclick=function(){
    window.location.href="..\Assignment2\index.php";
}
document.getElementById("b2").onclick=function(){
    window.location.href="..\Borrow\index.php";
}
document.getElementById("b3").onclick=function(){
    window.location.href="..\Assignment2\index.php";
}
document.getElementById("b4").onclick=function(){
    window.location.href="..\Assignment2\index.php";
}